### ISSUE TITLE
NEON optimization

### ISSUE THREAD

**Issue by donlk** [flanggut/smvs#3]
Is there any chance for NEON acceleration to be implemented? Any directives on how difficult would it be to provide NEON alternatives to SSE optimized blocks in smvs?
Also, why does mve and smvs use self-implemented data structures and math functions? Eigen is pretty mature in this area, providing in-place SIMD accelerations, why not use it?
thanks!

**Comment by flanggut** [comment]
I have never tried to optimize for ARM processors. My guess is that if NEON provides similar intrinsics as SEE it should be possible to essentially just replace the current SSE blocks with NEON intrinsics but that's definitely out of scope for myself.

Regarding optimization in general, I have ideas for making large parts of the code GPU accelerated because they can be easily expressed in shader operations. This would probably fit even better if you're aiming to run this on mobile devices. But it also requires quite a bit of engineering investment which I currently don't have the time for.

**Comment by donlk** [comment]
Thank you! Keep me posted please.
